// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_2d_cl_ss_ap_fixed_ap_fixed_16_5_5_3_0_config41_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_V_V_dout,
        data_V_V_empty_n,
        data_V_V_read,
        res_V_V_din,
        res_V_V_full_n,
        res_V_V_write
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_pp0_stage0 = 24'd16;
parameter    ap_ST_fsm_state7 = 24'd32;
parameter    ap_ST_fsm_state8 = 24'd64;
parameter    ap_ST_fsm_state9 = 24'd128;
parameter    ap_ST_fsm_state10 = 24'd256;
parameter    ap_ST_fsm_state11 = 24'd512;
parameter    ap_ST_fsm_state12 = 24'd1024;
parameter    ap_ST_fsm_state13 = 24'd2048;
parameter    ap_ST_fsm_state14 = 24'd4096;
parameter    ap_ST_fsm_state15 = 24'd8192;
parameter    ap_ST_fsm_state16 = 24'd16384;
parameter    ap_ST_fsm_state17 = 24'd32768;
parameter    ap_ST_fsm_state18 = 24'd65536;
parameter    ap_ST_fsm_state19 = 24'd131072;
parameter    ap_ST_fsm_state20 = 24'd262144;
parameter    ap_ST_fsm_state21 = 24'd524288;
parameter    ap_ST_fsm_state22 = 24'd1048576;
parameter    ap_ST_fsm_state23 = 24'd2097152;
parameter    ap_ST_fsm_state24 = 24'd4194304;
parameter    ap_ST_fsm_state25 = 24'd8388608;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] data_V_V_dout;
input   data_V_V_empty_n;
output   data_V_V_read;
output  [15:0] res_V_V_din;
input   res_V_V_full_n;
output   res_V_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data_V_V_read;
reg res_V_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [8:0] layer_in_V_6_address0;
reg    layer_in_V_6_ce0;
reg    layer_in_V_6_we0;
wire  signed [15:0] layer_in_V_6_q0;
reg   [31:0] sX_2;
reg   [31:0] sY_2;
reg   [31:0] pY_2;
reg   [31:0] pX_2;
wire   [8:0] w41_V_address0;
reg    w41_V_ce0;
wire   [252:0] w41_V_q0;
reg    data_V_V_blk_n;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln315_fu_1151_p2;
reg    res_V_V_blk_n;
wire    ap_CS_fsm_state24;
reg   [23:0] acc_V_31_0_reg_713;
reg   [23:0] acc_V_30_0_reg_725;
reg   [23:0] acc_V_29_0_reg_737;
reg   [23:0] acc_V_28_0_reg_749;
reg   [23:0] acc_V_27_0_reg_761;
reg   [23:0] acc_V_26_0_reg_773;
reg   [23:0] acc_V_25_0_reg_785;
reg   [23:0] acc_V_24_0_reg_797;
reg   [23:0] acc_V_23_0_reg_809;
reg   [23:0] acc_V_22_0_reg_821;
reg   [23:0] acc_V_21_0_reg_833;
reg   [23:0] acc_V_20_0_reg_845;
reg   [23:0] acc_V_19_0_reg_857;
reg   [23:0] acc_V_18_0_reg_869;
reg   [23:0] acc_V_17_0_reg_881;
reg   [23:0] acc_V_16_0_reg_893;
reg   [23:0] acc_V_15_0_reg_905;
reg   [23:0] acc_V_14_0_reg_917;
reg   [23:0] acc_V_13_0_reg_929;
reg   [23:0] acc_V_12_0_reg_941;
reg   [23:0] acc_V_11_0_reg_953;
reg   [23:0] acc_V_10_0_reg_965;
reg   [23:0] acc_V_9_0_reg_977;
reg   [23:0] acc_V_8_0_reg_989;
reg   [23:0] acc_V_7_0_reg_1001;
reg   [23:0] acc_V_6_0_reg_1013;
reg   [23:0] acc_V_5_0_reg_1025;
reg   [23:0] acc_V_4_0_reg_1037;
reg   [23:0] acc_V_3_0_reg_1049;
reg   [23:0] acc_V_2_0_reg_1061;
reg   [23:0] acc_V_1_0_reg_1073;
reg   [23:0] acc_V_0_0_reg_1085;
reg   [8:0] in_index_reg_1097;
reg    ap_block_state1;
wire   [6:0] i_fu_1145_p2;
reg   [6:0] i_reg_2558;
wire    ap_CS_fsm_state2;
wire   [5:0] i1_fu_1157_p2;
reg    ap_block_state3;
reg   [31:0] sX_2_load_reg_2571;
wire    ap_CS_fsm_state4;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_ready;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done;
wire   [0:0] icmp_ln326_fu_1172_p2;
reg   [0:0] icmp_ln326_reg_2576;
reg   [31:0] sY_2_load_reg_2581;
wire   [0:0] icmp_ln326_7_fu_1182_p2;
reg   [0:0] icmp_ln326_7_reg_2586;
reg   [31:0] pY_2_load_reg_2591;
reg   [31:0] pX_2_load_reg_2597;
wire   [0:0] and_ln326_6_fu_1240_p2;
reg   [0:0] and_ln326_6_reg_2603;
wire   [0:0] icmp_ln324_fu_1246_p2;
reg   [0:0] icmp_ln324_reg_2607;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [8:0] ir_fu_1252_p2;
reg    ap_enable_reg_pp0_iter0;
wire  signed [23:0] grp_fu_2139_p3;
reg    ap_enable_reg_pp0_iter1;
wire  signed [23:0] grp_fu_2147_p3;
wire  signed [23:0] grp_fu_2155_p3;
wire  signed [23:0] grp_fu_2163_p3;
wire  signed [23:0] grp_fu_2171_p3;
wire  signed [23:0] grp_fu_2179_p3;
wire  signed [23:0] grp_fu_2187_p3;
wire  signed [23:0] grp_fu_2195_p3;
wire  signed [23:0] grp_fu_2203_p3;
wire  signed [23:0] grp_fu_2211_p3;
wire  signed [23:0] grp_fu_2219_p3;
wire  signed [23:0] grp_fu_2227_p3;
wire  signed [23:0] grp_fu_2235_p3;
wire  signed [23:0] grp_fu_2243_p3;
wire  signed [23:0] grp_fu_2251_p3;
wire  signed [23:0] grp_fu_2259_p3;
wire  signed [23:0] grp_fu_2267_p3;
wire  signed [23:0] grp_fu_2275_p3;
wire  signed [23:0] grp_fu_2283_p3;
wire  signed [23:0] grp_fu_2291_p3;
wire  signed [23:0] grp_fu_2299_p3;
wire  signed [23:0] grp_fu_2307_p3;
wire  signed [23:0] grp_fu_2315_p3;
wire  signed [23:0] grp_fu_2323_p3;
wire  signed [23:0] grp_fu_2331_p3;
wire  signed [23:0] grp_fu_2339_p3;
wire  signed [23:0] grp_fu_2347_p3;
wire  signed [23:0] grp_fu_2355_p3;
wire  signed [23:0] grp_fu_2363_p3;
wire  signed [23:0] grp_fu_2371_p3;
wire  signed [23:0] grp_fu_2379_p3;
wire  signed [23:0] grp_fu_2387_p3;
reg   [15:0] trunc_ln708_230_reg_2786;
wire    ap_CS_fsm_state7;
reg   [15:0] trunc_ln708_231_reg_2791;
reg   [15:0] trunc_ln708_232_reg_2796;
reg   [15:0] trunc_ln708_233_reg_2801;
reg   [15:0] trunc_ln708_234_reg_2806;
reg   [15:0] trunc_ln708_235_reg_2811;
reg   [15:0] trunc_ln708_236_reg_2816;
reg   [15:0] trunc_ln708_237_reg_2821;
reg   [15:0] trunc_ln708_238_reg_2826;
reg   [15:0] trunc_ln708_239_reg_2831;
reg   [15:0] trunc_ln708_240_reg_2836;
reg   [15:0] trunc_ln708_241_reg_2841;
reg   [15:0] trunc_ln708_242_reg_2846;
reg   [15:0] trunc_ln708_243_reg_2851;
reg   [15:0] trunc_ln708_244_reg_2856;
reg   [15:0] trunc_ln708_245_reg_2861;
reg   [15:0] trunc_ln708_246_reg_2866;
reg   [15:0] trunc_ln708_247_reg_2871;
reg   [15:0] trunc_ln708_248_reg_2876;
reg   [15:0] trunc_ln708_249_reg_2881;
reg   [15:0] trunc_ln708_250_reg_2886;
reg   [15:0] trunc_ln708_251_reg_2891;
reg   [15:0] trunc_ln708_252_reg_2896;
reg   [15:0] trunc_ln708_253_reg_2901;
reg   [15:0] trunc_ln708_254_reg_2906;
reg   [15:0] trunc_ln708_255_reg_2911;
reg   [15:0] trunc_ln708_256_reg_2916;
reg   [15:0] trunc_ln708_257_reg_2921;
reg   [15:0] trunc_ln708_258_reg_2926;
reg   [15:0] trunc_ln708_259_reg_2931;
wire   [5:0] i_ic_fu_2042_p2;
reg   [5:0] i_ic_reg_2939;
wire    ap_CS_fsm_state23;
wire   [0:0] icmp_ln338_fu_2036_p2;
wire   [0:0] icmp_ln346_fu_2053_p2;
reg   [0:0] icmp_ln346_reg_2949;
wire   [31:0] select_ln356_fu_2120_p3;
wire   [0:0] icmp_ln350_fu_2099_p2;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state5;
reg   [4:0] tmpdata_V_address0;
reg    tmpdata_V_ce0;
reg    tmpdata_V_we0;
wire   [15:0] tmpdata_V_q0;
reg   [4:0] layer_out_i_address0;
reg    layer_out_i_ce0;
reg    layer_out_i_we0;
reg   [15:0] layer_out_i_d0;
wire   [15:0] layer_out_i_q0;
reg   [4:0] layer_out_i_address1;
reg    layer_out_i_ce1;
reg    layer_out_i_we1;
reg   [15:0] layer_out_i_d1;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_start;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_idle;
wire   [4:0] grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_data_V_address0;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_data_V_ce0;
wire   [8:0] grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_output_V_address0;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_output_V_ce0;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_output_V_we0;
wire   [15:0] grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_output_V_d0;
reg   [6:0] i_0_i_reg_691;
wire    ap_CS_fsm_state25;
reg   [5:0] i1_0_i_reg_702;
wire   [0:0] icmp_ln313_fu_1139_p2;
wire    ap_block_pp0_stage0;
reg   [5:0] i_ic_0_i_reg_1108;
wire    ap_CS_fsm_state22;
reg   [31:0] storemerge_i_reg_1119;
reg    grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_start_reg;
reg    ap_block_state3_ignore_call0;
wire   [63:0] zext_ln317_fu_1163_p1;
wire   [63:0] zext_ln332_fu_1258_p1;
wire   [63:0] zext_ln340_fu_2048_p1;
wire   [31:0] select_ln361_fu_2074_p3;
wire   [31:0] add_ln354_fu_2104_p2;
wire   [31:0] add_ln359_fu_2058_p2;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire   [30:0] tmp_7_fu_1192_p4;
wire   [30:0] tmp_8_fu_1212_p4;
wire   [0:0] icmp_ln326_8_fu_1202_p2;
wire   [0:0] icmp_ln326_9_fu_1222_p2;
wire   [0:0] and_ln326_5_fu_1234_p2;
wire   [0:0] and_ln326_fu_1228_p2;
wire  signed [15:0] sext_ln1116_fu_1268_p0;
wire  signed [7:0] trunc_ln332_fu_1264_p1;
wire  signed [7:0] tmp_378_fu_1280_p4;
wire  signed [7:0] tmp_379_fu_1294_p4;
wire  signed [7:0] tmp_380_fu_1308_p4;
wire  signed [7:0] tmp_381_fu_1322_p4;
wire  signed [7:0] tmp_382_fu_1336_p4;
wire  signed [7:0] tmp_383_fu_1350_p4;
wire  signed [7:0] tmp_384_fu_1364_p4;
wire  signed [7:0] tmp_385_fu_1378_p4;
wire  signed [7:0] tmp_386_fu_1392_p4;
wire  signed [7:0] tmp_387_fu_1406_p4;
wire  signed [7:0] tmp_388_fu_1420_p4;
wire  signed [7:0] tmp_389_fu_1434_p4;
wire  signed [7:0] tmp_390_fu_1448_p4;
wire  signed [7:0] tmp_391_fu_1462_p4;
wire  signed [7:0] tmp_392_fu_1476_p4;
wire  signed [7:0] tmp_393_fu_1490_p4;
wire  signed [7:0] tmp_394_fu_1504_p4;
wire  signed [7:0] tmp_395_fu_1518_p4;
wire  signed [7:0] tmp_396_fu_1532_p4;
wire  signed [7:0] tmp_397_fu_1546_p4;
wire  signed [7:0] tmp_398_fu_1560_p4;
wire  signed [7:0] tmp_399_fu_1574_p4;
wire  signed [7:0] tmp_400_fu_1588_p4;
wire  signed [7:0] tmp_401_fu_1602_p4;
wire  signed [7:0] tmp_402_fu_1616_p4;
wire  signed [7:0] tmp_403_fu_1630_p4;
wire  signed [7:0] tmp_404_fu_1644_p4;
wire  signed [7:0] tmp_405_fu_1658_p4;
wire  signed [7:0] tmp_406_fu_1672_p4;
wire  signed [7:0] tmp_407_fu_1686_p4;
wire  signed [4:0] tmp_21_fu_1700_p4;
wire   [31:0] add_ln361_fu_2069_p2;
wire   [31:0] add_ln356_fu_2115_p2;
wire  signed [15:0] grp_fu_2139_p1;
wire  signed [23:0] sext_ln1116_fu_1268_p1;
wire  signed [15:0] grp_fu_2147_p1;
wire  signed [15:0] grp_fu_2155_p1;
wire  signed [15:0] grp_fu_2163_p1;
wire  signed [15:0] grp_fu_2171_p1;
wire  signed [15:0] grp_fu_2179_p1;
wire  signed [15:0] grp_fu_2187_p1;
wire  signed [15:0] grp_fu_2195_p1;
wire  signed [15:0] grp_fu_2203_p1;
wire  signed [15:0] grp_fu_2211_p1;
wire  signed [15:0] grp_fu_2219_p1;
wire  signed [15:0] grp_fu_2227_p1;
wire  signed [15:0] grp_fu_2235_p1;
wire  signed [15:0] grp_fu_2243_p1;
wire  signed [15:0] grp_fu_2251_p1;
wire  signed [15:0] grp_fu_2259_p1;
wire  signed [15:0] grp_fu_2267_p1;
wire  signed [15:0] grp_fu_2275_p1;
wire  signed [15:0] grp_fu_2283_p1;
wire  signed [15:0] grp_fu_2291_p1;
wire  signed [15:0] grp_fu_2299_p1;
wire  signed [15:0] grp_fu_2307_p1;
wire  signed [15:0] grp_fu_2315_p1;
wire  signed [15:0] grp_fu_2323_p1;
wire  signed [15:0] grp_fu_2331_p1;
wire  signed [15:0] grp_fu_2339_p1;
wire  signed [15:0] grp_fu_2347_p1;
wire  signed [15:0] grp_fu_2355_p1;
wire  signed [15:0] grp_fu_2363_p1;
wire  signed [15:0] grp_fu_2371_p1;
wire  signed [15:0] grp_fu_2379_p1;
reg   [23:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_662;
reg    ap_condition_664;
reg    ap_condition_456;
reg    ap_condition_600;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 24'd1;
#0 sX_2 = 32'd0;
#0 sY_2 = 32'd0;
#0 pY_2 = 32'd0;
#0 pX_2 = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_start_reg = 1'b0;
end

conv_2d_cl_ss_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_layAem #(
    .DataWidth( 16 ),
    .AddressRange( 288 ),
    .AddressWidth( 9 ))
layer_in_V_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer_in_V_6_address0),
    .ce0(layer_in_V_6_ce0),
    .we0(layer_in_V_6_we0),
    .d0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_output_V_d0),
    .q0(layer_in_V_6_q0)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_w41_V #(
    .DataWidth( 253 ),
    .AddressRange( 288 ),
    .AddressWidth( 9 ))
w41_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w41_V_address0),
    .ce0(w41_V_ce0),
    .q0(w41_V_q0)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_tmpBew #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
tmpdata_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmpdata_V_address0),
    .ce0(tmpdata_V_ce0),
    .we0(tmpdata_V_we0),
    .d0(data_V_V_dout),
    .q0(tmpdata_V_q0)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_16_5_5_3_0_config32_s_layxdS #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
layer_out_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer_out_i_address0),
    .ce0(layer_out_i_ce0),
    .we0(layer_out_i_we0),
    .d0(layer_out_i_d0),
    .q0(layer_out_i_q0),
    .address1(layer_out_i_address1),
    .ce1(layer_out_i_ce1),
    .we1(layer_out_i_we1),
    .d1(layer_out_i_d1)
);

cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_start),
    .ap_done(grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done),
    .ap_idle(grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_idle),
    .ap_ready(grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_ready),
    .data_V_address0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_data_V_address0),
    .data_V_ce0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_data_V_ce0),
    .data_V_q0(tmpdata_V_q0),
    .output_V_address0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_output_V_address0),
    .output_V_ce0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_output_V_ce0),
    .output_V_we0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_output_V_we0),
    .output_V_d0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_output_V_d0),
    .output_V_q0(layer_in_V_6_q0)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U234(
    .din0(trunc_ln332_fu_1264_p1),
    .din1(grp_fu_2139_p1),
    .din2(acc_V_0_0_reg_1085),
    .dout(grp_fu_2139_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U235(
    .din0(tmp_378_fu_1280_p4),
    .din1(grp_fu_2147_p1),
    .din2(acc_V_1_0_reg_1073),
    .dout(grp_fu_2147_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U236(
    .din0(tmp_379_fu_1294_p4),
    .din1(grp_fu_2155_p1),
    .din2(acc_V_2_0_reg_1061),
    .dout(grp_fu_2155_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U237(
    .din0(tmp_380_fu_1308_p4),
    .din1(grp_fu_2163_p1),
    .din2(acc_V_3_0_reg_1049),
    .dout(grp_fu_2163_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U238(
    .din0(tmp_381_fu_1322_p4),
    .din1(grp_fu_2171_p1),
    .din2(acc_V_4_0_reg_1037),
    .dout(grp_fu_2171_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U239(
    .din0(tmp_382_fu_1336_p4),
    .din1(grp_fu_2179_p1),
    .din2(acc_V_5_0_reg_1025),
    .dout(grp_fu_2179_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U240(
    .din0(tmp_383_fu_1350_p4),
    .din1(grp_fu_2187_p1),
    .din2(acc_V_6_0_reg_1013),
    .dout(grp_fu_2187_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U241(
    .din0(tmp_384_fu_1364_p4),
    .din1(grp_fu_2195_p1),
    .din2(acc_V_7_0_reg_1001),
    .dout(grp_fu_2195_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U242(
    .din0(tmp_385_fu_1378_p4),
    .din1(grp_fu_2203_p1),
    .din2(acc_V_8_0_reg_989),
    .dout(grp_fu_2203_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U243(
    .din0(tmp_386_fu_1392_p4),
    .din1(grp_fu_2211_p1),
    .din2(acc_V_9_0_reg_977),
    .dout(grp_fu_2211_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U244(
    .din0(tmp_387_fu_1406_p4),
    .din1(grp_fu_2219_p1),
    .din2(acc_V_10_0_reg_965),
    .dout(grp_fu_2219_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U245(
    .din0(tmp_388_fu_1420_p4),
    .din1(grp_fu_2227_p1),
    .din2(acc_V_11_0_reg_953),
    .dout(grp_fu_2227_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U246(
    .din0(tmp_389_fu_1434_p4),
    .din1(grp_fu_2235_p1),
    .din2(acc_V_12_0_reg_941),
    .dout(grp_fu_2235_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U247(
    .din0(tmp_390_fu_1448_p4),
    .din1(grp_fu_2243_p1),
    .din2(acc_V_13_0_reg_929),
    .dout(grp_fu_2243_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U248(
    .din0(tmp_391_fu_1462_p4),
    .din1(grp_fu_2251_p1),
    .din2(acc_V_14_0_reg_917),
    .dout(grp_fu_2251_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U249(
    .din0(tmp_392_fu_1476_p4),
    .din1(grp_fu_2259_p1),
    .din2(acc_V_15_0_reg_905),
    .dout(grp_fu_2259_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U250(
    .din0(tmp_393_fu_1490_p4),
    .din1(grp_fu_2267_p1),
    .din2(acc_V_16_0_reg_893),
    .dout(grp_fu_2267_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U251(
    .din0(tmp_394_fu_1504_p4),
    .din1(grp_fu_2275_p1),
    .din2(acc_V_17_0_reg_881),
    .dout(grp_fu_2275_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U252(
    .din0(tmp_395_fu_1518_p4),
    .din1(grp_fu_2283_p1),
    .din2(acc_V_18_0_reg_869),
    .dout(grp_fu_2283_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U253(
    .din0(tmp_396_fu_1532_p4),
    .din1(grp_fu_2291_p1),
    .din2(acc_V_19_0_reg_857),
    .dout(grp_fu_2291_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U254(
    .din0(tmp_397_fu_1546_p4),
    .din1(grp_fu_2299_p1),
    .din2(acc_V_20_0_reg_845),
    .dout(grp_fu_2299_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U255(
    .din0(tmp_398_fu_1560_p4),
    .din1(grp_fu_2307_p1),
    .din2(acc_V_21_0_reg_833),
    .dout(grp_fu_2307_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U256(
    .din0(tmp_399_fu_1574_p4),
    .din1(grp_fu_2315_p1),
    .din2(acc_V_22_0_reg_821),
    .dout(grp_fu_2315_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U257(
    .din0(tmp_400_fu_1588_p4),
    .din1(grp_fu_2323_p1),
    .din2(acc_V_23_0_reg_809),
    .dout(grp_fu_2323_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U258(
    .din0(tmp_401_fu_1602_p4),
    .din1(grp_fu_2331_p1),
    .din2(acc_V_24_0_reg_797),
    .dout(grp_fu_2331_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U259(
    .din0(tmp_402_fu_1616_p4),
    .din1(grp_fu_2339_p1),
    .din2(acc_V_25_0_reg_785),
    .dout(grp_fu_2339_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U260(
    .din0(tmp_403_fu_1630_p4),
    .din1(grp_fu_2347_p1),
    .din2(acc_V_26_0_reg_773),
    .dout(grp_fu_2347_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U261(
    .din0(tmp_404_fu_1644_p4),
    .din1(grp_fu_2355_p1),
    .din2(acc_V_27_0_reg_761),
    .dout(grp_fu_2355_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U262(
    .din0(tmp_405_fu_1658_p4),
    .din1(grp_fu_2363_p1),
    .din2(acc_V_28_0_reg_749),
    .dout(grp_fu_2363_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U263(
    .din0(tmp_406_fu_1672_p4),
    .din1(grp_fu_2371_p1),
    .din2(acc_V_29_0_reg_737),
    .dout(grp_fu_2371_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U264(
    .din0(tmp_407_fu_1686_p4),
    .din1(grp_fu_2379_p1),
    .din2(acc_V_30_0_reg_725),
    .dout(grp_fu_2379_p3)
);

myproject_mac_muladd_5s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_5s_16s_24ns_24_1_1_U265(
    .din0(tmp_21_fu_1700_p4),
    .din1(layer_in_V_6_q0),
    .din2(acc_V_31_0_reg_713),
    .dout(grp_fu_2387_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln313_fu_1139_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state5);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_start_reg <= 1'b0;
    end else begin
        if ((~((icmp_ln315_fu_1151_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1151_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_start_reg <= 1'b1;
        end else if ((grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_ready == 1'b1)) begin
            grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_0_0_reg_1085 <= grp_fu_2139_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_0_0_reg_1085 <= 24'd16762880;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_10_0_reg_965 <= grp_fu_2219_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_10_0_reg_965 <= 24'd20480;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_11_0_reg_953 <= grp_fu_2227_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_11_0_reg_953 <= 24'd16771072;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_12_0_reg_941 <= grp_fu_2235_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_12_0_reg_941 <= 24'd30720;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_13_0_reg_929 <= grp_fu_2243_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_13_0_reg_929 <= 24'd8192;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_14_0_reg_917 <= grp_fu_2251_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_14_0_reg_917 <= 24'd16721920;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_15_0_reg_905 <= grp_fu_2259_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_15_0_reg_905 <= 24'd16769024;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_16_0_reg_893 <= grp_fu_2267_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_16_0_reg_893 <= 24'd16775168;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_17_0_reg_881 <= grp_fu_2275_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_17_0_reg_881 <= 24'd16760832;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_18_0_reg_869 <= grp_fu_2283_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_18_0_reg_869 <= 24'd16764928;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_19_0_reg_857 <= grp_fu_2291_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_19_0_reg_857 <= 24'd30720;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_1_0_reg_1073 <= grp_fu_2147_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_1_0_reg_1073 <= 24'd16771072;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_20_0_reg_845 <= grp_fu_2299_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_20_0_reg_845 <= 24'd2048;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_21_0_reg_833 <= grp_fu_2307_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_21_0_reg_833 <= 24'd16742400;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_22_0_reg_821 <= grp_fu_2315_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_22_0_reg_821 <= 24'd16771072;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_23_0_reg_809 <= grp_fu_2323_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_23_0_reg_809 <= 24'd16754688;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_24_0_reg_797 <= grp_fu_2331_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_24_0_reg_797 <= 24'd14336;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_25_0_reg_785 <= grp_fu_2339_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_25_0_reg_785 <= 24'd16758784;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_26_0_reg_773 <= grp_fu_2347_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_26_0_reg_773 <= 24'd26624;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_27_0_reg_761 <= grp_fu_2355_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_27_0_reg_761 <= 24'd16773120;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_28_0_reg_749 <= grp_fu_2363_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_28_0_reg_749 <= 24'd8192;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_29_0_reg_737 <= grp_fu_2371_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_29_0_reg_737 <= 24'd20480;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_2_0_reg_1061 <= grp_fu_2155_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_2_0_reg_1061 <= 24'd16766976;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_30_0_reg_725 <= grp_fu_2379_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_30_0_reg_725 <= 24'd16723968;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_31_0_reg_713 <= grp_fu_2387_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_31_0_reg_713 <= 24'd16764928;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_3_0_reg_1049 <= grp_fu_2163_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_3_0_reg_1049 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_4_0_reg_1037 <= grp_fu_2171_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_4_0_reg_1037 <= 24'd16771072;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_5_0_reg_1025 <= grp_fu_2179_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_5_0_reg_1025 <= 24'd32768;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_6_0_reg_1013 <= grp_fu_2187_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_6_0_reg_1013 <= 24'd16775168;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_7_0_reg_1001 <= grp_fu_2195_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_7_0_reg_1001 <= 24'd51200;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_8_0_reg_989 <= grp_fu_2203_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_8_0_reg_989 <= 24'd16748544;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2607 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_9_0_reg_977 <= grp_fu_2211_p3;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_9_0_reg_977 <= 24'd16746496;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln315_fu_1151_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1151_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i1_0_i_reg_702 <= i1_fu_1157_p2;
    end else if (((icmp_ln313_fu_1139_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i1_0_i_reg_702 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        i_0_i_reg_691 <= i_reg_2558;
    end else if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_i_reg_691 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        i_ic_0_i_reg_1108 <= i_ic_reg_2939;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        i_ic_0_i_reg_1108 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_fu_1246_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_index_reg_1097 <= ir_fu_1252_p2;
    end else if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        in_index_reg_1097 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        if ((1'b1 == ap_condition_664)) begin
            pX_2 <= 32'd0;
        end else if ((1'b1 == ap_condition_662)) begin
            pX_2 <= add_ln359_fu_2058_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        if ((1'b1 == ap_condition_600)) begin
            pY_2 <= 32'd0;
        end else if ((1'b1 == ap_condition_456)) begin
            pY_2 <= add_ln354_fu_2104_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        if ((1'b1 == ap_condition_664)) begin
            sX_2 <= 32'd0;
        end else if ((1'b1 == ap_condition_662)) begin
            sX_2 <= select_ln361_fu_2074_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        if ((1'b1 == ap_condition_600)) begin
            storemerge_i_reg_1119 <= 32'd0;
        end else if ((1'b1 == ap_condition_456)) begin
            storemerge_i_reg_1119 <= select_ln356_fu_2120_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        and_ln326_6_reg_2603 <= and_ln326_6_fu_1240_p2;
        icmp_ln326_7_reg_2586 <= icmp_ln326_7_fu_1182_p2;
        icmp_ln326_reg_2576 <= icmp_ln326_fu_1172_p2;
        pX_2_load_reg_2597 <= pX_2;
        pY_2_load_reg_2591 <= pY_2;
        sX_2_load_reg_2571 <= sX_2;
        sY_2_load_reg_2581 <= sY_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln326_6_reg_2603) & (1'b1 == ap_CS_fsm_state23))) begin
        i_ic_reg_2939 <= i_ic_fu_2042_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_2558 <= i_fu_1145_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln324_reg_2607 <= icmp_ln324_fu_1246_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state23) & ((1'd0 == and_ln326_6_reg_2603) | (icmp_ln338_fu_2036_p2 == 1'd1)))) begin
        icmp_ln346_reg_2949 <= icmp_ln346_fu_2053_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln346_reg_2949 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        sY_2 <= storemerge_i_reg_1119;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        trunc_ln708_230_reg_2786 <= {{acc_V_2_0_reg_1061[22:7]}};
        trunc_ln708_231_reg_2791 <= {{acc_V_3_0_reg_1049[22:7]}};
        trunc_ln708_232_reg_2796 <= {{acc_V_4_0_reg_1037[22:7]}};
        trunc_ln708_233_reg_2801 <= {{acc_V_5_0_reg_1025[22:7]}};
        trunc_ln708_234_reg_2806 <= {{acc_V_6_0_reg_1013[22:7]}};
        trunc_ln708_235_reg_2811 <= {{acc_V_7_0_reg_1001[22:7]}};
        trunc_ln708_236_reg_2816 <= {{acc_V_8_0_reg_989[22:7]}};
        trunc_ln708_237_reg_2821 <= {{acc_V_9_0_reg_977[22:7]}};
        trunc_ln708_238_reg_2826 <= {{acc_V_10_0_reg_965[22:7]}};
        trunc_ln708_239_reg_2831 <= {{acc_V_11_0_reg_953[22:7]}};
        trunc_ln708_240_reg_2836 <= {{acc_V_12_0_reg_941[22:7]}};
        trunc_ln708_241_reg_2841 <= {{acc_V_13_0_reg_929[22:7]}};
        trunc_ln708_242_reg_2846 <= {{acc_V_14_0_reg_917[22:7]}};
        trunc_ln708_243_reg_2851 <= {{acc_V_15_0_reg_905[22:7]}};
        trunc_ln708_244_reg_2856 <= {{acc_V_16_0_reg_893[22:7]}};
        trunc_ln708_245_reg_2861 <= {{acc_V_17_0_reg_881[22:7]}};
        trunc_ln708_246_reg_2866 <= {{acc_V_18_0_reg_869[22:7]}};
        trunc_ln708_247_reg_2871 <= {{acc_V_19_0_reg_857[22:7]}};
        trunc_ln708_248_reg_2876 <= {{acc_V_20_0_reg_845[22:7]}};
        trunc_ln708_249_reg_2881 <= {{acc_V_21_0_reg_833[22:7]}};
        trunc_ln708_250_reg_2886 <= {{acc_V_22_0_reg_821[22:7]}};
        trunc_ln708_251_reg_2891 <= {{acc_V_23_0_reg_809[22:7]}};
        trunc_ln708_252_reg_2896 <= {{acc_V_24_0_reg_797[22:7]}};
        trunc_ln708_253_reg_2901 <= {{acc_V_25_0_reg_785[22:7]}};
        trunc_ln708_254_reg_2906 <= {{acc_V_26_0_reg_773[22:7]}};
        trunc_ln708_255_reg_2911 <= {{acc_V_27_0_reg_761[22:7]}};
        trunc_ln708_256_reg_2916 <= {{acc_V_28_0_reg_749[22:7]}};
        trunc_ln708_257_reg_2921 <= {{acc_V_29_0_reg_737[22:7]}};
        trunc_ln708_258_reg_2926 <= {{acc_V_30_0_reg_725[22:7]}};
        trunc_ln708_259_reg_2931 <= {{acc_V_31_0_reg_713[22:7]}};
    end
end

always @ (*) begin
    if ((icmp_ln324_fu_1246_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln313_fu_1139_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln313_fu_1139_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln315_fu_1151_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_V_blk_n = data_V_V_empty_n;
    end else begin
        data_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln315_fu_1151_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1151_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_V_read = 1'b1;
    end else begin
        data_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer_in_V_6_address0 = zext_ln332_fu_1258_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        layer_in_V_6_address0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_output_V_address0;
    end else begin
        layer_in_V_6_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer_in_V_6_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        layer_in_V_6_ce0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_output_V_ce0;
    end else begin
        layer_in_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        layer_in_V_6_we0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_output_V_we0;
    end else begin
        layer_in_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        layer_out_i_address0 = zext_ln340_fu_2048_p1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_address0 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_address0 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_address0 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_address0 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_address0 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_address0 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_address0 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_address0 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_address0 = 64'd0;
    end else begin
        layer_out_i_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_address1 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_address1 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_address1 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_address1 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_address1 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_address1 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_address1 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_address1 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_address1 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_address1 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_address1 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_address1 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_address1 = 64'd1;
    end else begin
        layer_out_i_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state7))) begin
        layer_out_i_ce0 = 1'b1;
    end else begin
        layer_out_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state7))) begin
        layer_out_i_ce1 = 1'b1;
    end else begin
        layer_out_i_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_d0 = trunc_ln708_258_reg_2926;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_d0 = trunc_ln708_256_reg_2916;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_d0 = trunc_ln708_254_reg_2906;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_d0 = trunc_ln708_252_reg_2896;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_d0 = trunc_ln708_250_reg_2886;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_d0 = trunc_ln708_248_reg_2876;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_d0 = trunc_ln708_246_reg_2866;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_d0 = trunc_ln708_244_reg_2856;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_d0 = trunc_ln708_242_reg_2846;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_d0 = trunc_ln708_240_reg_2836;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_d0 = trunc_ln708_238_reg_2826;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_d0 = trunc_ln708_236_reg_2816;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_d0 = trunc_ln708_234_reg_2806;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_d0 = trunc_ln708_232_reg_2796;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_d0 = trunc_ln708_230_reg_2786;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_d0 = {{acc_V_0_0_reg_1085[22:7]}};
    end else begin
        layer_out_i_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_d1 = trunc_ln708_259_reg_2931;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_d1 = trunc_ln708_257_reg_2921;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_d1 = trunc_ln708_255_reg_2911;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_d1 = trunc_ln708_253_reg_2901;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_d1 = trunc_ln708_251_reg_2891;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_d1 = trunc_ln708_249_reg_2881;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_d1 = trunc_ln708_247_reg_2871;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_d1 = trunc_ln708_245_reg_2861;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_d1 = trunc_ln708_243_reg_2851;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_d1 = trunc_ln708_241_reg_2841;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_d1 = trunc_ln708_239_reg_2831;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_d1 = trunc_ln708_237_reg_2821;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_d1 = trunc_ln708_235_reg_2811;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_d1 = trunc_ln708_233_reg_2801;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_d1 = trunc_ln708_231_reg_2791;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_d1 = {{acc_V_1_0_reg_1073[22:7]}};
    end else begin
        layer_out_i_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state7))) begin
        layer_out_i_we0 = 1'b1;
    end else begin
        layer_out_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state7))) begin
        layer_out_i_we1 = 1'b1;
    end else begin
        layer_out_i_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        res_V_V_blk_n = res_V_V_full_n;
    end else begin
        res_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        res_V_V_write = 1'b1;
    end else begin
        res_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln315_fu_1151_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmpdata_V_address0 = zext_ln317_fu_1163_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmpdata_V_address0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_data_V_address0;
    end else begin
        tmpdata_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln315_fu_1151_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1151_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmpdata_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmpdata_V_ce0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_data_V_ce0;
    end else begin
        tmpdata_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln315_fu_1151_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1151_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmpdata_V_we0 = 1'b1;
    end else begin
        tmpdata_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w41_V_ce0 = 1'b1;
    end else begin
        w41_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln313_fu_1139_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((icmp_ln315_fu_1151_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1151_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((icmp_ln315_fu_1151_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1151_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'd1 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'd0 == and_ln326_6_fu_1240_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln324_fu_1246_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln324_fu_1246_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((1'b1 == ap_CS_fsm_state23) & ((1'd0 == and_ln326_6_reg_2603) | (icmp_ln338_fu_2036_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln354_fu_2104_p2 = (pY_2_load_reg_2591 + 32'd1);

assign add_ln356_fu_2115_p2 = (sY_2_load_reg_2581 + 32'd1);

assign add_ln359_fu_2058_p2 = (pX_2_load_reg_2597 + 32'd1);

assign add_ln361_fu_2069_p2 = (sX_2_load_reg_2571 + 32'd1);

assign and_ln326_5_fu_1234_p2 = (icmp_ln326_9_fu_1222_p2 & icmp_ln326_8_fu_1202_p2);

assign and_ln326_6_fu_1240_p2 = (and_ln326_fu_1228_p2 & and_ln326_5_fu_1234_p2);

assign and_ln326_fu_1228_p2 = (icmp_ln326_fu_1172_p2 & icmp_ln326_7_fu_1182_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((icmp_ln315_fu_1151_p2 == 1'd0) & (data_V_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_ignore_call0 = ((icmp_ln315_fu_1151_p2 == 1'd0) & (data_V_V_empty_n == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_456 = (((icmp_ln350_fu_2099_p2 == 1'd0) & (1'd0 == and_ln326_6_reg_2603) & (icmp_ln346_fu_2053_p2 == 1'd1)) | ((icmp_ln350_fu_2099_p2 == 1'd0) & (icmp_ln346_fu_2053_p2 == 1'd1) & (icmp_ln338_fu_2036_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_600 = (((1'd0 == and_ln326_6_reg_2603) & (icmp_ln350_fu_2099_p2 == 1'd1) & (icmp_ln346_fu_2053_p2 == 1'd1)) | ((icmp_ln350_fu_2099_p2 == 1'd1) & (icmp_ln346_fu_2053_p2 == 1'd1) & (icmp_ln338_fu_2036_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_662 = (((icmp_ln346_fu_2053_p2 == 1'd0) & (1'd0 == and_ln326_6_reg_2603)) | ((icmp_ln346_fu_2053_p2 == 1'd0) & (icmp_ln338_fu_2036_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_664 = (((1'd0 == and_ln326_6_reg_2603) & (icmp_ln346_fu_2053_p2 == 1'd1)) | ((icmp_ln346_fu_2053_p2 == 1'd1) & (icmp_ln338_fu_2036_p2 == 1'd1)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_start = grp_cnnshift_arr_ap_fixed_ap_fixed_16_5_5_3_0_config41_s_fu_1130_ap_start_reg;

assign grp_fu_2139_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2147_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2155_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2163_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2171_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2179_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2187_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2195_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2203_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2211_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2219_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2227_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2235_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2243_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2251_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2259_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2267_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2275_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2283_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2291_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2299_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2307_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2315_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2323_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2331_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2339_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2347_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2355_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2363_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2371_p1 = sext_ln1116_fu_1268_p1;

assign grp_fu_2379_p1 = sext_ln1116_fu_1268_p1;

assign i1_fu_1157_p2 = (i1_0_i_reg_702 + 6'd1);

assign i_fu_1145_p2 = (i_0_i_reg_691 + 7'd1);

assign i_ic_fu_2042_p2 = (i_ic_0_i_reg_1108 + 6'd1);

assign icmp_ln313_fu_1139_p2 = ((i_0_i_reg_691 == 7'd100) ? 1'b1 : 1'b0);

assign icmp_ln315_fu_1151_p2 = ((i1_0_i_reg_702 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln324_fu_1246_p2 = ((in_index_reg_1097 == 9'd288) ? 1'b1 : 1'b0);

assign icmp_ln326_7_fu_1182_p2 = ((sY_2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln326_8_fu_1202_p2 = (($signed(tmp_7_fu_1192_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln326_9_fu_1222_p2 = (($signed(tmp_8_fu_1212_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln326_fu_1172_p2 = ((sX_2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln338_fu_2036_p2 = ((i_ic_0_i_reg_1108 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln346_fu_2053_p2 = ((pX_2_load_reg_2597 == 32'd9) ? 1'b1 : 1'b0);

assign icmp_ln350_fu_2099_p2 = ((pY_2_load_reg_2591 == 32'd9) ? 1'b1 : 1'b0);

assign ir_fu_1252_p2 = (in_index_reg_1097 + 9'd1);

assign res_V_V_din = layer_out_i_q0;

assign select_ln356_fu_2120_p3 = ((icmp_ln326_7_reg_2586[0:0] === 1'b1) ? 32'd2 : add_ln356_fu_2115_p2);

assign select_ln361_fu_2074_p3 = ((icmp_ln326_reg_2576[0:0] === 1'b1) ? 32'd2 : add_ln361_fu_2069_p2);

assign sext_ln1116_fu_1268_p0 = layer_in_V_6_q0;

assign sext_ln1116_fu_1268_p1 = sext_ln1116_fu_1268_p0;

assign tmp_21_fu_1700_p4 = {{w41_V_q0[252:248]}};

assign tmp_378_fu_1280_p4 = {{w41_V_q0[15:8]}};

assign tmp_379_fu_1294_p4 = {{w41_V_q0[23:16]}};

assign tmp_380_fu_1308_p4 = {{w41_V_q0[31:24]}};

assign tmp_381_fu_1322_p4 = {{w41_V_q0[39:32]}};

assign tmp_382_fu_1336_p4 = {{w41_V_q0[47:40]}};

assign tmp_383_fu_1350_p4 = {{w41_V_q0[55:48]}};

assign tmp_384_fu_1364_p4 = {{w41_V_q0[63:56]}};

assign tmp_385_fu_1378_p4 = {{w41_V_q0[71:64]}};

assign tmp_386_fu_1392_p4 = {{w41_V_q0[79:72]}};

assign tmp_387_fu_1406_p4 = {{w41_V_q0[87:80]}};

assign tmp_388_fu_1420_p4 = {{w41_V_q0[95:88]}};

assign tmp_389_fu_1434_p4 = {{w41_V_q0[103:96]}};

assign tmp_390_fu_1448_p4 = {{w41_V_q0[111:104]}};

assign tmp_391_fu_1462_p4 = {{w41_V_q0[119:112]}};

assign tmp_392_fu_1476_p4 = {{w41_V_q0[127:120]}};

assign tmp_393_fu_1490_p4 = {{w41_V_q0[135:128]}};

assign tmp_394_fu_1504_p4 = {{w41_V_q0[143:136]}};

assign tmp_395_fu_1518_p4 = {{w41_V_q0[151:144]}};

assign tmp_396_fu_1532_p4 = {{w41_V_q0[159:152]}};

assign tmp_397_fu_1546_p4 = {{w41_V_q0[167:160]}};

assign tmp_398_fu_1560_p4 = {{w41_V_q0[175:168]}};

assign tmp_399_fu_1574_p4 = {{w41_V_q0[183:176]}};

assign tmp_400_fu_1588_p4 = {{w41_V_q0[191:184]}};

assign tmp_401_fu_1602_p4 = {{w41_V_q0[199:192]}};

assign tmp_402_fu_1616_p4 = {{w41_V_q0[207:200]}};

assign tmp_403_fu_1630_p4 = {{w41_V_q0[215:208]}};

assign tmp_404_fu_1644_p4 = {{w41_V_q0[223:216]}};

assign tmp_405_fu_1658_p4 = {{w41_V_q0[231:224]}};

assign tmp_406_fu_1672_p4 = {{w41_V_q0[239:232]}};

assign tmp_407_fu_1686_p4 = {{w41_V_q0[247:240]}};

assign tmp_7_fu_1192_p4 = {{pY_2[31:1]}};

assign tmp_8_fu_1212_p4 = {{pX_2[31:1]}};

assign trunc_ln332_fu_1264_p1 = w41_V_q0[7:0];

assign w41_V_address0 = zext_ln332_fu_1258_p1;

assign zext_ln317_fu_1163_p1 = i1_0_i_reg_702;

assign zext_ln332_fu_1258_p1 = in_index_reg_1097;

assign zext_ln340_fu_2048_p1 = i_ic_0_i_reg_1108;

endmodule //conv_2d_cl_ss_ap_fixed_ap_fixed_16_5_5_3_0_config41_s
